# Inventory for VPN Gateway Projekt
# Maskiner som ska konfigureras av Ansible

[gateway]
gateway-vm ansible_host=192.168.56.10

[internal]
internal-vm ansible_host=192.168.56.20

[all:vars]
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3
